web:
    build: .
    volumes:
        - .:/usr/src/app:rw
    links:
        - db
    ports:
        - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
db:
    image: mysql:5.6.24
    volumes:
        - mysql/my.cnf:/etc/mysql/my.cnf:ro
        - mysql/data:/var/lib/mysql:rw
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cedemo
        MYSQL_USER: cedemo
        MYSQL_PASSWORD: cedemo
